### ISSUE TITLE
Failed to execute command autogypi (npm install)

### ISSUE THREAD

**Issue by bpetto35** [charto/nbind-example-universal#3]
Failed to execute the command on my ubuntu 17.04 box
autogypi -r build && node-gyp -C build/asmjs  configure build --asmjs=1 && copyasm build/asmjs dist

`gyp ERR! build error `
`gyp ERR! stack Error: 'make' failed with exit code: 2`
`gyp ERR! stack     at ChildProcess.onExit (/home/bruno/nbind-example-universal/node_modules/node-gyp/lib/build.js:258:23)`
`gyp ERR! stack     at emitTwo (events.js:87:13)`
`gyp ERR! stack     at ChildProcess.emit (events.js:172:7)`
`gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)`
`gyp ERR! System Linux 4.10.0-22-generic`
`gyp ERR! command "/usr/bin/nodejs" "/home/bruno/nbind-example-universal/node_modules/.bin/node-gyp" "-C" "build/asmjs" "configure" "build" "--asmjs=1"`
`gyp ERR! cwd /home/bruno/nbind-example-universal/build/asmjs`
`gyp ERR! node -v v4.7.2`
`gyp ERR! node-gyp -v v3.6.2`
`gyp ERR! not ok `
`npm ERR! Linux 4.10.0-22-generic`
`npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build:asmjs"`
`npm ERR! node v4.7.2`
`npm ERR! npm  v3.5.2`
`npm ERR! code ELIFECYCLE`
`npm ERR! nbind-example-universal@0.2.0 build:asmjs: 'autogypi -r build && node-gyp -C build/asmjs  configure build --asmjs=1 && copyasm build/asmjs dist'`
`npm ERR! Exit status 1`
`npm ERR!` 
`npm ERR! Failed at the nbind-example-universal@0.2.0 build:asmjs script 'autogypi -r build && node-gyp -C build/asmjs  configure build --asmjs=1 && copyasm build/asmjs dist'.`
`npm ERR! Make sure you have the latest version of node.js and npm installed.`
`npm ERR! If you do, this is most likely a problem with the nbind-example-universal package,`
`npm ERR! not with npm itself.`
`npm ERR! Tell the author that this fails on your system:`
`npm ERR!     autogypi -r build && node-gyp -C build/asmjs  configure build --asmjs=1 && copyasm build/asmjs dist`
`npm ERR! You can get information on how to open an issue for this project with:`
`npm ERR!     npm bugs nbind-example-universal`
`npm ERR! Or if that isn't available, you can get their info via:`
`npm ERR!     npm owner ls nbind-example-universal`
`npm ERR! There is likely additional logging output above.`
`npm ERR! Please include the following file with any support request:`
`npm ERR!     /home/bruno/nbind-example-universal/npm-debug.log`
`Warning: problems with asm.js build`

**Comment by jjrv** [comment]
Before the lines you pasted, was there something like this?

```
nbind-example-universal/node_modules/nbind/bin/emcc: line 21: emcc: command not found
```

In any case, does `npm test` still work? It sounds like you don't have Emscripten installed. That means the example will fail to compile an asm.js fallback, but the native code will still work.

This example demonstrates producing a fallback for users without a working C++ compiler, but does not include the fallback. You need Emscripten to produce the fallback, but it will still work without it, for users who do have some other C++ compiler.

**Comment by bpetto35** [comment]
Result of npm test

    npm test

    > nbind-example-universal@0.2.0 test /home/bruno/nbind-example-universal
    > node dist/example.js

    Platform: native

Is that ok?

Sorry for the delay.

**Comment by jjrv** [comment]
Yes, it's working correctly. The C++ code it executes is:

```C++
    static std::string test() {
#       if defined(BUILDING_NODE_EXTENSION)
            return("native");
#       elif defined(EMSCRIPTEN)
            return("asm.js");
#       else
            return("unknown");
#       endif
    }
```

It's reporting that the function was compiled as a Node.js binary addon, and got called correctly.

**Comment by KrishnaPG** [comment]
Getting the same error.
````
> autogypi -r build && node-gyp -C build/asmjs  configure build --asmjs=1 && copyasm build/asmjs dist

make: Entering directory '/home/osboxes/workspace/nbind-example-universal/build/asmjs/build'
  COPY Release/obj.target/nbind/geni/pre.js
  COPY Release/obj.target/nbind/geni/post.js
  COPY Release/obj.target/nbind/geni/em-api.js
  CXX(target) Release/obj.target/nbind/../../node_modules/nbind/src/common.o
/home/osboxes/workspace/nbind-example-universal/node_modules/nbind/bin/emcc: 21: /home/osboxes/workspace/nbind-example-universal/node_modules/nbind/bin/emcc: emcc: not found
nbind.target.mk:148: recipe for target 'Release/obj.target/nbind/../../node_modules/nbind/src/common.o' failed
make: *** [Release/obj.target/nbind/../../node_modules/nbind/src/common.o] Error 127
make: Leaving directory '/home/osboxes/workspace/nbind-example-universal/build/asmjs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
````
`emcc` not found. and 
````
$ npm test

> nbind-example-universal@0.2.0 test /home/osboxes/workspace/nbind-example-universal
> node dist/example.js

Platform: native
````
Environment:
````
osboxes@osboxes ~/workspace/nbind-example-universal $ node -v
v7.7.4

osboxes@osboxes ~/workspace/nbind-example-universal $ g++ --version
g++ (Ubuntu 7.1.0-10ubuntu1~16.04.york0) 7.1.0
````
How to resolve this?

**Comment by KrishnaPG** [comment]
Alright. When run the commands explicitly from command-line `node dist/serve.js` it started the app.

When visited the `localhost:<port>` it is showing `Platform: asm.js`

Is that the expected result? 

Where is it getting this `asm.js` version, when I built it for native? How to force it to use the native (i.e., I want the html to talk to the node-js http-server and then that server talks to the c++ function and returns the results) - how to achieve it?

**Comment by jjrv** [comment]
This example ships with a precompiled asm.js binary, which runs if your computer fails to compile it.

It uses the native binary first, if available. However, the native binary cannot work in a browser, you'd need to run the app in [Electron](https://electron.atom.io/) to do that.

If you want to run C++ code on the server and have it talk to the browser, you'll need to write a suitable server component and make a request from the browser. This is done like any other AJAX call.

This example only runs the C++ code directly in the browser.
